### ISSUE TITLE
[BUG]: opfunu install in mac

### ISSUE THREAD

**Issue by najmehn00** [thieu1995/opfunu#14]
### Description of the bug

hi i cant install opfunu . i installed before but now in visual studio i cant use it does any one have a solution?

### Steps To Reproduce

i install step by step  to read me file

**Comment by thieu1995** [comment]
@najmehn00 ,

Have you selected the environment in VS code? Can you show me the capture of the error?

**Comment by thieu1995** [comment]
No comment from @najmehn00 ,
Im gonna close this one.
