### ISSUE TITLE
[BUG]: A bug in cec2020.F82020(ndim=10)

### ISSUE THREAD

**Issue by RuiZhong961230** [thieu1995/opfunu#20]
### Description of the bug

Dear Thieu
I hope to find you well.
cec2020.F82020(ndim=10) seems to have a bug that the fitness value may be smaller than 0
and in the official technical report, the minimum is 2100.
Best wishes

### Steps To Reproduce

You can directly copy the following code:

from opfunu.cec_based import cec2020

func = cec2020.F82020(ndim=10)
print(func.evaluate([90.75118764, 97.00278372, 76.1721669, 99.96999972, -11.39271999, 89.5915097, 76.24025183, 83.30977968,  23.79283718, 37.22928422]))

where the 10-D solution [90.75118764, 97.00278372, 76.1721669, 99.96999972, -11.39271999, 89.5915097, 76.24025183, 83.30977968,  23.79283718, 37.22928422] is within the search space in [-100, 100]

**Comment by thieupu** [comment]
Hi @RuiZhong961230 ,

Which version are you using? 
In the latest version, @firestrand has fixed some bugs in these functions. I don't know if it cause this one or not.

**Comment by RuiZhong961230** [comment]
Thank you @thieu1995 for your reply.
And I use the latest version 1.0.1 of opfunu.

**Comment by RuiZhong961230** [comment]
@thieu1995 Thank you for your reply
I recently replicated the latest metaheuristic algorithm: "Growth Optimizer: A powerful metaheuristic algorithm for solving continuous and discrete global optimization problems".
This algorithm found the position of that I mentioned before :)

**Comment by thieupu** [comment]
@RuiZhong961230 ,
Thank you. I will try that algorithm. 
By the way, I'm curious, I saw you have used Coati Optimization Algorithm. I know it is not my job but I think you should check other algorithms of the same authors Eva Trojovská, Pavel Trojovský such as Fennec For Optimization, Northern Goshawk Optimization, Osprey Optimization Algorithm, Pelican Optimization Algorithm, Serval Optimization Algorithm,... and compare them together. You will see something there. I think you know what I am talking about. 
In case you don't, please check it here: https://github.com/thieu1995/mealpy
Cheers.

**Comment by RuiZhong961230** [comment]
Thank you for your advice. Actually, I think many scholars have noticed the
similarities of these so-called novel meta heuristics. I am also curious
why their papers can pass the peer-review while my paper always received
rejection. 🥹

thieupu ***@***.***>于2023年10月3日 周二21:10写道：

**Comment by thieupu** [comment]
@RuiZhong961230 ,

Yes, I know your feelings. That is why we should avoid and boycott these kind of algorithms as much as possible.

**Comment by RuiZhong961230** [comment]
Thank you for your advices, I definitely agree with you.

thieupu ***@***.***>于2023年10月3日 周二21:36写道：

**Comment by firestrand** [comment]
I realize I didn’t increment the package version after fixing the bugs, using the code from latest should fix any CEC issue as all are passing tests for optimal values.

**Comment by thieu1995** [comment]
@firestrand. I know it passed the tests for optimal values. However, there are some solutions that can make the function smaller than 0 like @RuiZhong961230 said above. I think there is a bug somewhere. Can you check it?

**Comment by thieu1995** [comment]
@RuiZhong961230,

I will close this issue now. Feel free to open it. It seems the problem has been fixed. I will release new version.

**Comment by RuiZhong961230** [comment]
I appreciate your effort in maintaining this library

Nguyen Van Thieu ***@***.***>于2024年3月22日 周五19:59写道：
