### ISSUE TITLE
[BUG]: cec2021 F2 has abnormal optimal value.

### ISSUE THREAD

**Issue by SkyLull** [thieu1995/opfunu#21]
## In short: 

F22021 should have a global optimal value = 1100.0, but I found much more space that has even lower values.

---

## In detail:

The plotted function of F22021 looked like this:
![螢幕擷取畫面 2023-12-15 155906](https://github.com/thieu1995/opfunu/assets/65713587/c2031735-9b63-4f48-9f30-7c6b9603639a)
The very little red dot near the middle (located at *(2.0990197e+01, -2.3188216e+01)*, right as provided) should have the global optimal value of **1100.0** (equals bias), but as the plot clearly showed, much more space has a value lower than 1100.0.
For example, the red dot located at *(94.14767894, 2.33460048)* near the right side solved for a value of **23.98**, there even exists a point *(99.31320785, -0.51136206)* that solved for a value of **-32.35**

I suppose this is not the intended outcome?

In case I did something wrong that I couldn't find myself due to the lack of domain knowledge, here is the same plot from other angles:
![圖片](https://github.com/thieu1995/opfunu/assets/65713587/91110b3d-f4dd-4d0a-9b21-d8fa85349069)
![螢幕擷取畫面 2023-12-15 160801](https://github.com/thieu1995/opfunu/assets/65713587/9b53b954-d75e-4ea4-849d-f553697ca75a)
![螢幕擷取畫面 2023-12-15 163427](https://github.com/thieu1995/opfunu/assets/65713587/c41abc23-5af7-45bc-8bc3-2522a4d97341)

### Steps To Reproduce

I use this code to draw the plot:
```python
import numpy as np
import matplotlib.pyplot as plt
import opfunu.cec_based


if __name__ == '__main__':
    dim = 2
    eval_func = opfunu.cec_based.F22021(ndim=2)
    bound = {"upper": 100.0,
             "lower": -100.0}

    # Create a meshgrid for visualization
    x = np.linspace(bound["lower"], bound["upper"], 300)
    y = np.linspace(bound["lower"], bound["upper"], 300)
    X, Y = np.meshgrid(x, y)

    Z = np.zeros_like(X)
    for i in range(len(x)):
        for j in range(len(y)):
            Z[i, j] = eval_func.evaluate([X[i, j], Y[i, j]])

    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.plot_surface(X, Y, Z, cmap='viridis')
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_zlabel('z')

    print("f_global = ", eval_func.f_global)

    ax.scatter(2.0990197e+01, -2.3188216e+01, 1100., color='red')

    plt.show()
```

### Additional Information

The version of main packages:
Python           3.9.13
Cython              3.0.6
matplotlib          3.8.2
numpy               1.26.2
opfunu              1.0.1

using Windows 11 22H2

**Comment by thieu1995** [comment]
Hi @SkyLull,

Please install the previous version 1.0.0. This bug will be gone. This latest version has this bug but I haven't had time to fix it.
