### ISSUE TITLE
[BUG] Typo in OddSquare function: `np.p` instead of `np.pi`

### ISSUE THREAD

**Issue by mpvanderschelling** [thieu1995/opfunu#25]
## Problem

When evaluating the `OddSquare` function, an `AttributeError` is raised.
This is possible because there is a typo in the function: `np.p` is not an attribute of `numpy`

https://github.com/thieu1995/opfunu/blob/092327e4928564ee946bc77cf2a3c24b3cb54922/opfunu/name_based/o_func.py#L56

## Possible solution

Change to `np.pi`, as I think this is the correct expression

**Comment by thieu1995** [comment]
@mpvanderschelling,

Thank you, I have fixed this problem.
