### ISSUE TITLE
[BUG]: Wrong `self._bounds` index used for setting `self._ndim`

### ISSUE THREAD

**Issue by mpvanderschelling** [thieu1995/opfunu#26]
## Problem

When presented a funciton where `ndim` cannot be 2 (if `dim_changeable=False` and `default_dim != 2`) and `ndim=None` is given upon initialization, this function makes it so the dimension is set to 2, because the wrong index is given when setting `self._ndim = self._bounds.shape[1]`.

https://github.com/thieu1995/opfunu/blob/092327e4928564ee946bc77cf2a3c24b3cb54922/opfunu/benchmark.py#L84

# Possible solution

This should be the first index (`self._bounds.shape[0]`). This is correctly implemented in the `cec_based` submodule

**Comment by thieu1995** [comment]
@mpvanderschelling,

You are right. This problem has been fixed. Thank you.
