### ISSUE TITLE
[BUG]: Mishra07 function: np has no method factorial

### ISSUE THREAD

**Issue by mpvanderschelling** [thieu1995/opfunu#28]
### Description of the bug

The Mishra Function has an operation calling `np.factorial`. This method does not exist

### Steps To Reproduce

1. Create an instance of the opfunu.name_based.m_func.Mishra07 function
2. evaluate the function

**Comment by thieu1995** [comment]
@mpvanderschelling,

Thank you, this problem has been fixed.
