### ISSUE TITLE
[BUG]: Use visualize.py failed

### ISSUE THREAD

**Issue by Gang1024** [thieu1995/opfunu#32]
### Description of the bug

When I want to draw a 2d or 3d image by plot_2d or plot_3d in visualize.py, it will report an error. 
**Error Message :** "ValueError: too many values to unpack (expected 2). "
It happens on the first line of both two functions: X_domain, Y_domain = func.bounds. 
Here is my guess about cause of the error:
The variable "func.bounds" has dimension "dim_default",  it will be given to variable "X_domain" and "Y_domain".

### Steps To Reproduce

1.run visualize.plot_2d(cec2017.F12017())
2.ValueError: too many values to unpack (expected 2)

**Comment by thieu1995** [comment]
@Gang1024,

Thanks, it has been fixed in latest version. Wait for the release.
