### ISSUE TITLE
latex formula miss for Ackley02

### ISSUE THREAD

**Issue by guoyuejiang** [thieu1995/opfunu#33]
### Description of the bug

latex_formula = r'f_{\text{Ackley02}(x) = -200 e^{-0.02 \sqrt{x_1^2 + x_2^2}}'

it should be r'f_{\text{Ackley02}}(x) = -200 e^{-0.02 \sqrt{x_1^2 + x_2^2}' ?

### Steps To Reproduce

`latex_formula = r'f_{\text{Ackley02}(x) = -200 e^{-0.02 \sqrt{x_1^2 + x_2^2}}'`

**Comment by thieu1995** [comment]
@guoyuejiang,

I think you should check the equation again. It should has the } outside too.

**Comment by guoyuejiang** [comment]
yes, you are right, it should be:
f_{\text{Ackley02}}(x) = -200 e^{-0.02 \sqrt{x_1^2 + x_2^2}}

**Comment by guoyuejiang** [comment]
> @guoyuejiang,
> 
> I think you should check the equation again. It should has the } outside too.

yes, you are right, it should be:
f_{\text{Ackley02}}(x) = -200 e^{-0.02 \sqrt{x_1^2 + x_2^2}}

**Comment by thieu1995** [comment]
@guoyuejiang ,

No matter what, now you can draw your own equations. You can modify it and draw it using latest version. If you see any error on any equation, you can change it and draw it.

**Comment by guoyuejiang** [comment]
@thieu1995 Yes, thx for the update
