### ISSUE TITLE
[BUG]:  An error has been identified in the configuration parameters of Opfunu library.

### ISSUE THREAD

**Issue by Bardbo** [thieu1995/opfunu#34]
### Description of the bug

In cec2017.py, the parameter setting of the test function **F10: Hybrid Function 1** is erroneous. The parameter $p$ should be set to $[0.2, 0.4, 0.4]$.In a similar manner, the parameter $p$ in **F17: Hybrid Function 8** should be set to $[0.2, 0.2, 0.2, 0.2, 0.2, 0.2]$.

As not all test functions in the Opfunu library have been individually verified, it is not possible to ascertain whether there are other errors of a similar nature. Consequently, it is necessary to perform the requisite verification when the library is actually being utilized.

### Steps To Reproduce

Please review the **description of the bug** content and forgive me for my poor English

**Comment by thieu1995** [comment]
@Bardbo,

Thanks for pointing out. I will fix in next commit.
